# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true  # default
contact_links:
- name: ðŸ’¡ Feature Request
  url: https://github.com/chanzuckerberg/napari-hub/discussions/new?category=ideas
  about: |
  Have an feature request? Start an "Ideas" thread on our discussion forum.
- name: ðŸ¤· How do I?
  url: https://github.com/chanzuckerberg/napari-hub/discussions/new?category=q-a
  about: |
  Looking for help? Start a "Q&A" thread on our discussion forum.
